CREATE DATABASE IF NOT EXISTS CRYPTO_TRADING;

USE CRYPTO_TRADING;

-- TABLES STRUCTURES
CREATE TABLE IF NOT EXISTS ASSETS (
	ASSET_NAME			VARCHAR(10) NOT NULL,
	A_CLASS 			VARCHAR(20),
	ALT_NAME			VARCHAR(10),
	DECIMALS			INT,
	DISPLAY_DECIMALS	INT,
	START_TIME			BIGINT      NOT NULL,
	EXPIRE_TIME			BIGINT,
	PRIMARY KEY(ASSET_NAME, START_TIME)
);


CREATE TABLE IF NOT EXISTS ASSET_PAIRS (
	PAIR_ID				BIGINT		AUTO_INCREMENT PRIMARY KEY,
	PAIR_NAME			VARCHAR(20) NOT NULL,
	ALT_NAME			VARCHAR(20),
	A_CLASS_BASE		VARCHAR(20),
	BASE				VARCHAR(10),
	A_CLASS_QUOTE		VARCHAR(20),
	QUOTE				VARCHAR(10),
	LOT					VARCHAR(20),
	PAIR_DECIMALS		INT,
	LOT_DECIMALS		INT,
	LOT_MULTIPLIER		INT,
	FEE_VOLUME_CURRENCY	VARCHAR(10),
	MARGIN_CALL			INT,
	MARGIN_STOP			INT,
	START_TIME			BIGINT,
	EXPIRE_TIME			BIGINT
);
CREATE TABLE IF NOT EXISTS ASSET_PAIRS_FEE (
	PAIR_ID			BIGINT,
	FEE_TYPE		ENUM('fees', 'fees_maker'),
	VOLUME			INT,
	PERCENT_FEE		DECIMAL(10,5)
);
CREATE TABLE IF NOT EXISTS ASSET_PAIRS_LEVERAGE (
	PAIR_ID			BIGINT,
	LEVERAGE_TYPE	ENUM('buy', 'sell'),
	LEVERAGE_VALUE	INT
);


CREATE TABLE IF NOT EXISTS TICKERS (
    CALL_TIME		        BIGINT      NOT NULL,
	PAIR_NAME               VARCHAR(30) NOT NULL,
    ASK_PRICE		        DECIMAL(30,11),
	ASK_WHOLE_LOT_VOLUME    INT,
	ASK_LOT_VOLUME          DECIMAL(30,11),
    BID_PRICE		        DECIMAL(30,11),
	BID_WHOLE_LOT_VOLUME    INT,
	BID_LOT_VOLUME          DECIMAL(30,11),
    LAST_CLOSED_PRICE		DECIMAL(30,11),
	LAST_CLOSED_LOT_VOLUME  DECIMAL(30,11),
    VOLUME_TODAY		    DECIMAL(30,11),
	VOLUME_LAST_24          DECIMAL(30,11),
    VOLUME_WEIGHTED_AVERAGE_TODAY		DECIMAL(30,11),
	VOLUME_WEIGHTED_AVERAGE_LAST_24     DECIMAL(30,11),
    NUMBER_TRADES_TODAY		DECIMAL(30,11),
	NUMBER_TRADES_LAST_24   DECIMAL(30,11),
    LOW_TODAY		        DECIMAL(30,11),
	LOW_LAST_24             DECIMAL(30,11),
    HIGH_TODAY		        DECIMAL(30,11),
	HIGH_LAST_24            DECIMAL(30,11),
	OPENING_PRICE           DECIMAL(30,11),
	GRAFANA_TIME            DATETIME NOT NULL,

	PRIMARY KEY (CALL_TIME, PAIR_NAME)
);


CREATE TABLE IF NOT EXISTS CT_PROPERTIES (
    PROP_NAME       VARCHAR(50)     PRIMARY KEY,
    PROP_VALUE      VARCHAR(100)
);
INSERT INTO CT_PROPERTIES (PROP_NAME, PROP_VALUE) VALUES ('DOWNLOAD_ORDERS', '0');

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID		BIGINT AUTO_INCREMENT PRIMARY KEY,
    REF_ID          VARCHAR(30),
    USER_REF        VARCHAR(30),
    STATUS          ENUM('pending', 'open', 'closed', 'canceled', 'expired'),
    REASON          VARCHAR(100),   -- only for closed orders
    OPENTM          DECIMAL(30,11),
    CLOSETM         DECIMAL(30,11), -- only for closed orders
    STARTTM         DECIMAL(30,11),
    EXPIRETM        DECIMAL(30,11),
    VOL             DECIMAL(30,11),
    VOL_EXEC        DECIMAL(30,11),
    COST            DECIMAL(30,11),
    FEE             DECIMAL(30,11),
    PRICE           DECIMAL(30,11),
    MISC            VARCHAR(50),
    OFLAGS          VARCHAR(50),
    TRADES_IDX      VARCHAR(200),
    DESCR_PAIR_NAME     VARCHAR(20),
    DESCR_ORDER_ACTION  ENUM('buy', 'sell'),
    DESCR_ORDER_TYPE    ENUM('market', 'limit', 'stop-loss', 'take-profit', 'stop-loss-profit', 'stop-loss-profit-limit', 'stop-loss-limit', 'take-profit-limit', 'trailing-stop', 'trailing-stop-limit', 'stop-loss-and-limit', 'settle-position'),
    DESCR_PRICE         DECIMAL(30,11),
    DESCR_PRICE2        DECIMAL(30,11),
    DESCR_LEVERAGE      INT,
    DESCR_ORDER_DESCR   VARCHAR(100),
    DESCR_CLOSE_DESCR   VARCHAR(100)
)